spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Product_Transaction
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/db.master.xml

#logging:
#    level:
#      web: debug
#      root: debug