--liquibase formatted sql
--changeset yuvi:001.1
CREATE TABLE CATEGORIES(
CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
CATEGORY_NAME VARCHAR(200),
ACTIVE BOOLEAN,
CREATED_BY VARCHAR(50),
CREATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(50) ,
UPDATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT CATEGORY_ID_PK PRIMARY KEY (CATEGORY_ID)
);