--liquibase formatted sql
--changeset yuvi:002.1
CREATE TABLE PRODUCT_REFERENCE(
PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(200),
PRODUCT_DESC VARCHAR(500),
CATEGORY_ID INT NOT NULL,
ACTIVE BOOLEAN,
QUANTITY INT,
UNIT_PRICE DOUBLE(10,2),
CREATED_BY VARCHAR(50),
CREATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(50) ,
UPDATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID)
);